refactor!: remove "wallet" naming convention.
Polkadex-Substrate/polkadex-ts pull request #56
Opened 2023-12-15 23:10 UTC by nuel77

In the context of polkadex apps, a "Wallet" can be of two types - from an extension or stored locally,  both are places where multiple accounts are stored. So a wallet is defined by the where by who can access its accounts. Accounts stored by polkdot.js for example are only available via polkadot.js extension not through talisman. Each wallet can have multiple accounts which can be uniquely identified by the public key (address)  and can also have meta data like name and a password for decoding its private key.

2023-12-16 06:48 UTC, serhii-temchenko requested changes

2023-12-16 06:48 UTC, serhii-temchenko commented on packages/trade-wallet/src/index.ts
Why this file is removed? It is an entry point to the package. Is it even compiles without it?

2023-12-16 09:19 UTC, nuel77 commented on packages/trade-wallet/src/index.ts
the package is not removed, i renamed the entire folder from "trade-wallet" to "local-wallet" git is showing it as removed. but its just moved.

2023-12-16 15:46 UTC, serhii-temchenko commented on packages/trade-wallet/src/index.ts
oh I see, then [trade-wallet](https://github.com/Polkadex-Substrate/polkadex-ts/tree/refactor-naming/packages/trade-wallet) folder should be removed? but it is still there with `CHANGELOG.md` file in it...

2023-12-17 14:16 UTC, nuel77 commented on packages/trade-wallet/src/index.ts
removed.

2023-12-17 20:34 UTC, serhii-temchenko commented on packages/trade-wallet/src/index.ts
Thanks!

2023-12-17 20:34 UTC, serhii-temchenko approved these changes

2023-12-18 07:06 UTC, merged